/* Copyright (C) 2024 raould@gmail.com License: GPLv2 / GNU General
 * Public License, version 2
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
 */

var gWarning = ["WARNING:",
		"PHOTOSENSITIVITY/EPILEPSY/SEIZURES: A VERY SMALL",
		"PERCENTAGE OF INDIVIDUALS MAY EXPERIENCE",
		"EPILEPTIC SEIZURES OR BLACKOUTS WHEN EXPOSED TO",
		"CERTAIN LIGHT PATTERNS OR FLASHING LIGHTS.",
		"EXPOSURE TO CERTAIN PATTERNS OR BACKGROUNDS ON A",
		"TELEVISION SCREEN OR WHEN PLAYING VIDEO GAMES",
		"MAY TRIGGER EPILEPTIC SEIZURES OR BLACKOUTS IN",
		"THESE INDIVIDUALS. THESE CONDITIONS MAY TRIGGER",
		"PREVIOUSLY UNDETECTED EPILEPTIC SYMPTOMS OR",
		"SEIZURES IN PERSONS WHO HAVE NO HISTORY OF PRIOR",
		"SEIZURES OR EPILEPSY. IF YOU, OR ANYONE IN YOUR",
		"FAMILY, HAS AN EPILEPTIC CONDITION OR HAS HAD",
		"SEIZURES OF ANY KIND, CONSULT YOUR DOCTOR BEFORE",
		"PLAYING. IMMEDIATELY DISCONTINUE USE AND CONSULT",
		"YOUR DOCTOR BEFORE RESUMING GAMEPLAY IF YOU OR",
		"YOUR CHILD EXPERIENCE ANY OF THE FOLLOWING",
		"HEALTH PROBLEMS OR SYMPTOMS: DIZZINESS, ALTERED",
		"VISION, EYE OR MUSCLE TWITCHES, LOSS OF",
		"AWARENESS, DISORIENTATION, SEIZURES, OR ANY",
		"INVOLUNTARY MOVEMENT OR CONVULSION. RESUME",
		"GAMEPLAY ONLY ON APPROVAL OF YOUR DOCTOR."];
